### ISSUE TITLE
npm vulnerabilities

### ISSUE THREAD

**Issue by yjarosz** [elixir-luxembourg/daisy#51]
When running npm install we got warnings:

* With `docker-compose`

```
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
...
> node-sass@4.12.0 postinstall /static/vendor/node_modules/node-sass
> node scripts/build.js
...
npm WARN lifecycle elixir-daisy@1.0.0~prepare: cannot run in wd elixir-daisy@1.0.0 npm run build (wd=/static/vendor)
found 3 vulnerabilities (2 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

* With local install:

```
added 1 package from 1 contributor and audited 6178 packages in 8.848s
found 20 vulnerabilities (3 moderate, 17 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by neoflex** [comment]
do you know why we get different results? the package.json file is the same no?
Maybe because of different npm versions? older one in the docker version

**Comment by neoflex** [comment]
Most of the issues are fixed. We cannot upgrade yet to bootstrap 4.3.1 because bootstrap-material-design 4.1.1 is not compatible yet. 
bootstrap-material-design also requires cssnano-cli that requires an old version of js-yaml that has 'high' vulnerabilities. To solve this, we have to use package-lock.json to override the js-yaml version. As a result, we now need to install npm dependencies with `npm ci` instead of `npm install`. This will install the dependencies in package-lock.json instead of using package.json.
